### ISSUE TITLE
Strings are not always localized

### ISSUE THREAD

**Issue by iandunn** [Automattic/nearby-wordpress-events#19]
Reported by @glueckpress on [the call-for-feedback post](https://make.wordpress.org/community/2017/03/23/showing-upcoming-local-events-in-wp-admin/#comment-23208):

> One thing I noticed when testing the plugin with different languages is that it doesn’t support user language yet. When my site language is default en_US, and I switch my user language to de_DE, the core dashboard widget would localize the news feed. This plugin does not do that (yet), it always shows news from the English feed.

I'm seeing the news items localized (e.g., `WordPress 4.7.3 Sicherheits- und Wartungs-Release`), but not the rest of the text (e.g., `Attend an upcoming event near...`)

**Comment by glueckpress** [comment]
For clarification, this is how it looks for me in 0.1 (installed from .org).

News feed gets localized  according to site locale:

<img width="975" alt="screen shot 2017-03-24 at 10 08 12" src="https://cloud.githubusercontent.com/assets/308422/24287502/50634ac0-107a-11e7-8368-1c1ffc97ce9c.png">

…but not according to user locale:

<img width="918" alt="screen shot 2017-03-24 at 10 07 46" src="https://cloud.githubusercontent.com/assets/308422/24287522/5b713d64-107a-11e7-955b-729ff7060320.png">

Missing string localization currently seems in alignment with status of deployment on translate.w.org?

<img width="992" alt="screen shot 2017-03-24 at 10 13 43" src="https://cloud.githubusercontent.com/assets/308422/24287623/a6b689e6-107a-11e7-96be-84cd68bc4df5.png">

<img width="937" alt="screen shot 2017-03-24 at 10 17 21" src="https://cloud.githubusercontent.com/assets/308422/24287744/1b7ea33a-107b-11e7-8819-097c07e35fc8.png">

**Comment by iandunn** [comment]
@glueckpress, are you still seeing the unlocalized `Attend an upcoming event near...` with version `0.2`? On some of the sites I've tested, it looks like the language pack isn't being downloaded, but on others it is. Would you also mind logging in to 2015.us.wordcamp.org and checking there too (with Deutsch as your user locale)?

@mayukojpn, have you noticed any problems with strings like `Attend an upcoming event near...` not be localized into Japanese, or with the news feed not being localized? The plugin is also on 2017.tokyo.wordcamp.org if you wouldn't mind checking there too.

**Comment by glueckpress** [comment]
@iandunn 
> are you still seeing the unlocalized `Attend an upcoming event near...` with version `0.2`?

Nope, the localized string is displayed now. 👍 

I cannot access the Dashboard at 2015.us.wordcamp.org, and when I try to access my profile, it redirects to my profile page on w.org.

**Comment by mayukojpn** [comment]
LGTM except core news feed, Thanks!

**Comment by iandunn** [comment]
I think I tracked the feed issue down to [a Core bug](https://core.trac.wordpress.org/ticket/40417), so I'm going to go ahead and close this.

If anyone experiences any localization problems, though, let me know.
