### ISSUE TITLE
Add feedback button

### ISSUE THREAD

**Issue by iandunn** [Automattic/nearby-wordpress-events#21]
I think it might be helpful to add a feedback button somewhere in the widget, in order to encourage users to provide feedback while we're in the user-testing phase. It'd be removed during the merge to Core.

Maybe it could be a 4th link in the footer? I'm not sure.

It could link to [the announcement post on make/Community](https://make.wordpress.org/community/2017/03/23/showing-upcoming-local-events-in-wp-admin/), or maybe to the w.org support forums.

@mapk, what do you think?

**Comment by mapk** [comment]
I like this idea. It could look something like this:

![feedback-link](https://cloud.githubusercontent.com/assets/617986/24619486/f8376b1a-184e-11e7-8884-2a0e07a4d49b.png)

**Comment by coreymckrill** [comment]
Aside: have we tested what the bottom link bar would look like if it wrapped to two lines? Some translation strings might be a lot longer than the English. Adding that fourth link is what made me think of it...

**Comment by iandunn** [comment]
Thanks Mark :)

Good question about the line wrapping. I tested general responsiveness and IIRC, the line never wraps in English, even on the mobile view.  It'd be good to test that again with 4 items and in a few other languages

**Comment by iandunn** [comment]
Closing, because after a few days it doesn't seem like a high enough priority. We're soliciting feedback through a lot of other channels, and the people who are likely to install the beta are probably going to learn about it from one of those channels anyway.
