### ISSUE TITLE
Fix styles on small screens

### ISSUE THREAD

**Issue by iandunn** [Automattic/nearby-wordpress-events#28]
The layout doesn't work very well 2 columns of widgets at screen widths like these:

* 350px
* 800px
* 1002px

**Comment by iandunn** [comment]
If you set your location to `San Francisco`, the `Part 3- Site Maintenance - Tools to Make It Easy` event title wraps.

**Comment by coreymckrill** [comment]
I think the above commit fixes this, but I'd love some additional eyes on it. @iandunn @mapk

**Comment by iandunn** [comment]
I'm still seeing some problems in FF `54.0a2`:

### 308 x 664
![308x664](https://cloud.githubusercontent.com/assets/484068/24884298/9a3232ca-1dfd-11e7-951f-ea078ca8312a.png)

### 1064 x 664
![1064x684](https://cloud.githubusercontent.com/assets/484068/24884299/9a364e6e-1dfd-11e7-9738-059a3ff96a23.png)

### 1508 x 664
![1508x664](https://cloud.githubusercontent.com/assets/484068/24884297/9a316124-1dfd-11e7-9835-fe9e172d653f.png)

On the really small views, maybe we should change it to look more like this:

```
April 2017 Meetup (Topic TBD)
Oakland, CA, USA 
Sunday, Apr 16, 2017 - 1:00 pm

---

Flexbox + CSS Grid: Magic for Responsive Layouts
Oakland, CA, USA 
Sunday, Apr 16, 2017 - 1:00 pm

```

What do you think, @mapk?

**Comment by coreymckrill** [comment]
@iandunn Hmm, it looks like you didn't get the latest, or your browser is using cached styles. The really small view should look like what you are proposing above...

**Comment by iandunn** [comment]
D'oh, you're right, I updated the wrong install. It looks perfect now :)

**Comment by mapk** [comment]
Looks good to me too! Excellent fix.
